/**
 * The release pipeline's logic, tested away from GitHub.
 *
 * These cover the decisions that used to live in shell inside the workflow,
 * where they could only be exercised by cutting a real release. The cases
 * worth having are the ones that previously failed silently: a manifest with
 * no signature, a version that disagrees across platforms, and a tag that was
 * already published.
 */
import { readFileSync, readdirSync } from 'node:fs'
import { resolve } from 'node:path'

import { describe, expect, it } from 'vitest'

import {
  compareVersions,
  highestRelease,
  nextVersion,
  parseTag,
  resolveRelease
} from './resolve-release.mjs'
import { stampCargoLock, stampCargoToml, stampCrashReporterCfg, stampJsonVersion, VERSIONED_FILES, withLfEndings, workspaceCrates } from './stamp-versions.mjs'
import {
  assertManifestComplete,
  buildManifest,
  mergeManifests,
  PLATFORM_KEYS
} from './update-manifest.mjs'
import { missingAssetKinds, requiredAssets, verifyRelease } from './verify-release-assets.mjs'

describe('resolve-release', () => {
  it('reads stable and candidate tags, and rejects anything else', () => {
    expect(parseTag('v1.2.3')).toMatchObject({ major: 1, minor: 2, patch: 3, rc: null })
    expect(parseTag('v1.2.3-rc.4')).toMatchObject({ major: 1, minor: 2, patch: 3, rc: 4 })
    expect(parseTag('1.2.3')).toMatchObject({ version: '1.2.3' })
    expect(parseTag('v1.2')).toBeNull()
    expect(parseTag('nightly-v1.2.3')).toBeNull()
    expect(parseTag(undefined)).toBeNull()
  })

  it('sorts a candidate below its own stable release', () => {
    expect(compareVersions(parseTag('v1.0.0-rc.1'), parseTag('v1.0.0'))).toBeLessThan(0)
    expect(compareVersions(parseTag('v1.0.0-rc.1'), parseTag('v1.0.0-rc.2'))).toBeLessThan(0)
    expect(compareVersions(parseTag('v0.9.9'), parseTag('v1.0.0-rc.1'))).toBeLessThan(0)
    expect(highestRelease(['v0.1.3', 'v0.2.0-rc.0', 'v0.1.9'])).toMatchObject({ version: '0.2.0-rc.0' })
  })

  it('ignores tags that are not releases when picking the next version', () => {
    expect(nextVersion('patch', ['v0.1.3', 'not-a-tag', 'v0.1.2'])).toBe('0.1.4')
  })

  it('starts at 0.1.0 in a repository with no releases', () => {
    expect(nextVersion('patch', [])).toBe('0.1.0')
    expect(nextVersion('rc', [])).toBe('0.1.0-rc.0')
  })

  it('walks the candidate counter, then promotes it to its own stable', () => {
    expect(nextVersion('rc', ['v0.1.3'])).toBe('0.1.4-rc.0')
    expect(nextVersion('rc', ['v0.1.4-rc.0'])).toBe('0.1.4-rc.1')
    // Promoting must not skip 0.1.4 and land on 0.1.5.
    expect(nextVersion('patch', ['v0.1.3', 'v0.1.4-rc.1'])).toBe('0.1.4')
  })

  it('bumps minor and major from the highest release', () => {
    expect(nextVersion('minor', ['v0.1.3'])).toBe('0.2.0')
    expect(nextVersion('major', ['v0.1.3'])).toBe('1.0.0')
  })

  it('keeps a candidate out of the updater endpoint', () => {
    const rc = resolveRelease({ ref: 'v0.2.0-rc.0', tags: ['v0.1.3'] })
    expect(rc).toMatchObject({ isPrerelease: true, makeLatest: false, previousTag: 'v0.1.3' })
    const stable = resolveRelease({ ref: 'v0.2.0', tags: ['v0.1.3'] })
    expect(stable).toMatchObject({ isPrerelease: false, makeLatest: true })
  })

  it('refuses to cut a version that was already published', () => {
    expect(() => resolveRelease({ version: '0.1.3', tags: ['v0.1.3'] })).toThrow(/already exists/)
    // A tag push is re-runnable: the tag existing is the trigger, not a clash.
    expect(() => resolveRelease({ ref: 'v0.1.3', tags: ['v0.1.3'] })).not.toThrow()
  })

  it('leaves previousTag empty for a first release, so notes are not generated against nothing', () => {
    expect(resolveRelease({ ref: 'v0.1.0', tags: [] }).previousTag).toBe('')
  })

  it('rejects a ref or version that is not a release', () => {
    expect(() => resolveRelease({ ref: 'main' })).toThrow(/Not a release tag/)
    expect(() => resolveRelease({ version: 'latest' })).toThrow(/Not a valid version/)
  })
})

describe('a CRLF checkout', () => {
  // Windows converts to CRLF on checkout, and every stamper here anchors on
  // `^`/`$` or splits on "\n[[package]]\n". A release once failed outright
  // with "Cargo.lock has no [[package]] entries" for exactly this reason.
  // Shaped like the real file: a header, then the packages.
  const lock = [
    '# This file is automatically @generated by Cargo.',
    'version = 4',
    '',
    '[[package]]',
    'name = "dive-desktop"',
    'version = "0.1.0"',
    ''
  ].join('\r\n')

  it('is stamped, and keeps the endings it arrived with', () => {
    const out = withLfEndings(lock, (text) => stampCargoLock(text, '1.2.3', ['dive-desktop']))
    expect(out).toContain('version = "1.2.3"')
    expect(out).toContain('\r\n')
    // Every newline is still a CRLF: none were left bare by the round trip.
    expect(out.split('\n').length).toBe(out.split('\r\n').length)
  })

  it('leaves an LF file alone', () => {
    const lf = lock.replaceAll('\r\n', '\n')
    const out = withLfEndings(lf, (text) => stampCargoLock(text, '1.2.3', ['dive-desktop']))
    expect(out).not.toContain('\r')
    expect(out).toContain('version = "1.2.3"')
  })
})

describe('every release script can tell it is the entry point', () => {
  // This is a Windows-only failure and macOS cannot see it. `process.argv[1]`
  // there is a drive path, so `file://${process.argv[1]}` is
  // `file://D:\\a\\x.mjs` while `import.meta.url` is `file:///D:/a/x.mjs`.
  // The comparison never matches, the main block never runs, and the script
  // exits 0 having done nothing -- which is how a release once bundled an
  // installer stamped with the previous version.
  it('compares argv to import.meta.url as a URL, not by pasting a prefix', () => {
    const dir = resolve(import.meta.dirname)
    const scripts = readdirSync(dir).filter((f) => f.endsWith('.mjs') && !f.endsWith('.test.mjs'))
    expect(scripts.length).toBeGreaterThan(0)
    for (const file of scripts) {
      const source = readFileSync(resolve(dir, file), 'utf8')
      expect(source, `${file} builds a file:// URL by hand`).not.toMatch(
        /`file:\/\/\$\{process\.argv\[1\]\}`/
      )
      if (source.includes('process.argv[1]')) {
        expect(source, `${file} should compare with pathToFileURL`).toMatch(/pathToFileURL/)
      }
    }
  })
})

describe('stamp-versions', () => {
  it('replaces only the workspace version in Cargo.toml', () => {
    const source = '[workspace]\nmembers = ["a"]\n\n[workspace.package]\nversion = "0.1.3"\nedition = "2024"\n'
    const stamped = stampCargoToml(source, '0.2.0')
    expect(stamped).toContain('version = "0.2.0"')
    expect(stamped).toContain('edition = "2024"')
    expect(stamped).toContain('members = ["a"]')
  })

  it('replaces the first top-level version in a JSON manifest without reformatting it', () => {
    const source = '{\n  "productName": "Dive",\n  "version": "0.1.3",\n  "identifier": "app.dive"\n}\n'
    expect(stampJsonVersion(source, '0.2.0', 'tauri.conf.json')).toBe(
      '{\n  "productName": "Dive",\n  "version": "0.2.0",\n  "identifier": "app.dive"\n}\n'
    )
  })

  it('replaces only ProductVersion in the crashpad config', () => {
    const source = '[Config]\nProductName=Dive\nProductVersion=0.1.0\nAppName=Dive\n'
    expect(stampCrashReporterCfg(source, '0.2.0')).toBe('[Config]\nProductName=Dive\nProductVersion=0.2.0\nAppName=Dive\n')
  })

  it('fails loudly when a manifest has no version to stamp', () => {
    expect(() => stampCargoToml('[workspace]\n', '1.0.0')).toThrow(/workspace.package/)
    expect(() => stampJsonVersion('{}', '1.0.0', 'x.json')).toThrow(/version/)
    expect(() => stampCrashReporterCfg('[Config]\n', '1.0.0')).toThrow(/ProductVersion/)
  })

  const lock = [
    '# This file is automatically @generated by Cargo.',
    'version = 4',
    '',
    '[[package]]',
    'name = "anyhow"',
    'version = "1.0.99"',
    'source = "registry+https://github.com/rust-lang/crates.io-index"',
    '',
    '[[package]]',
    'name = "dive-core"',
    'version = "0.1.3"',
    'dependencies = ["anyhow"]',
    '',
    // A vendored path dependency: no `source`, but not ours to version.
    '[[package]]',
    'name = "tauri-runtime-cef"',
    'version = "0.1.0"',
    'dependencies = ["anyhow"]',
    ''
  ].join('\n')

  it('stamps only the named workspace crates in Cargo.lock', () => {
    const stamped = stampCargoLock(lock, '0.1.4', ['dive-core'])
    expect(stamped).toContain('name = "dive-core"\nversion = "0.1.4"')
    expect(stamped).toContain('name = "anyhow"\nversion = "1.0.99"')
    // The regression this guards: a vendored crate has no `source` line either.
    expect(stamped).toContain('name = "tauri-runtime-cef"\nversion = "0.1.0"')
    // The header's own `version = 4` is the lockfile format, not a crate.
    expect(stamped).toContain('version = 4\n')
  })

  it('is a no-op when the lockfile already carries the version', () => {
    expect(stampCargoLock(lock, '0.1.3', ['dive-core'])).toBe(lock)
  })

  it('fails when a workspace crate is missing from the lockfile, which means drift', () => {
    expect(() => stampCargoLock(lock, '1.0.0', ['dive-core', 'dive-ghost'])).toThrow(/dive-ghost/)
    expect(() => stampCargoLock('version = 4\n', '1.0.0', ['x'])).toThrow(/no \[\[package\]\]/)
  })

  it('resolves the real workspace: every member inherits the version, the vendored crate does not', () => {
    // vitest runs from apps/desktop and rewrites import.meta.url to /@fs/…, so
    // the repository root is two levels above the working directory.
    const names = workspaceCrates(resolve(process.cwd(), '../..'))
    expect(names).toEqual([
      'dive-agent', 'dive-cdp', 'dive-core', 'dive-desktop', 'dive-integration', 'dive-mcp'
    ])
    expect(names).not.toContain('tauri-runtime-cef')
  })

  it('names every manifest that carries the app version', () => {
    expect(VERSIONED_FILES).toEqual([
      'Cargo.toml',
      'Cargo.lock',
      'apps/desktop/package.json',
      'apps/desktop/src-tauri/tauri.conf.json',
      'apps/desktop/src-tauri/cef/crash_reporter.cfg'
    ])
  })
})

describe('update-manifest', () => {
  const base = {
    version: '0.1.4',
    target: 'aarch64-apple-darwin',
    archive: '/build/Dive.app.tar.gz',
    signature: 'SIGNATURE',
    baseUrl: 'https://github.com/o/r/releases/download/v0.1.4',
    pubDate: '2026-01-01T00:00:00Z'
  }

  it('builds a manifest whose URL points at an actual file', () => {
    const manifest = buildManifest(base)
    expect(manifest.platforms['darwin-aarch64']).toEqual({
      signature: 'SIGNATURE',
      url: 'https://github.com/o/r/releases/download/v0.1.4/Dive.app.tar.gz'
    })
    expect(manifest.notes).toBe('Dive 0.1.4')
  })

  it('refuses the empty signature the old shell heredoc would have published', () => {
    expect(() => buildManifest({ ...base, signature: '' })).toThrow(/signature/)
    expect(() => buildManifest({ ...base, signature: '   \n' })).toThrow(/signature/)
  })

  it('refuses a missing archive rather than emitting a URL with no filename', () => {
    expect(() => buildManifest({ ...base, archive: '' })).toThrow(/archive/)
    expect(() => buildManifest({ ...base, archive: '/build/Dive.dmg' })).toThrow(/tar\.gz/)
  })

  it('rejects a target with no updater platform key', () => {
    expect(() => buildManifest({ ...base, target: 'x86_64-unknown-linux-gnu' })).toThrow(/platform key/)
    expect(Object.values(PLATFORM_KEYS)).toEqual([
      'darwin-aarch64',
      'darwin-x86_64',
      'windows-x86_64'
    ])
  })

  it('wants each platform\'s own archive shape, not one fixed extension', () => {
    const win = { ...base, target: 'x86_64-pc-windows-msvc' }
    // On Windows the signed installer is the updater archive.
    expect(
      buildManifest({ ...win, archive: '/build/Dive_1.2.3_x64-setup.exe' })
        .platforms['windows-x86_64'].url
    ).toMatch(/Dive_1\.2\.3_x64-setup\.exe$/)
    // A macOS archive under a Windows target is a build matrix wired wrong,
    // and would publish a manifest that only fails on someone's machine.
    expect(() => buildManifest({ ...win, archive: '/build/Dive.app.tar.gz' })).toThrow(/-setup\.exe/)
    expect(() => buildManifest({ ...base, archive: '/build/Dive_1.2.3_x64-setup.exe' })).toThrow(
      /tar\.gz/
    )
  })

  it('merges one platform per architecture into a single manifest', () => {
    const arm = buildManifest(base)
    const intel = buildManifest({
      ...base,
      target: 'x86_64-apple-darwin',
      archive: '/build/Dive-x64.app.tar.gz',
      signature: 'SIGNATURE-X64'
    })
    const merged = mergeManifests([arm, intel])
    expect(Object.keys(merged.platforms)).toEqual(['darwin-aarch64', 'darwin-x86_64'])
    expect(merged.version).toBe('0.1.4')
  })

  it('catches a matrix that built two versions, which would ship the wrong binary', () => {
    const arm = buildManifest(base)
    const stale = buildManifest({ ...base, version: '0.1.3', target: 'x86_64-apple-darwin' })
    expect(() => mergeManifests([arm, stale])).toThrow(/disagree on the version/)
  })

  it('catches the same platform arriving twice, which would silently drop one', () => {
    expect(() => mergeManifests([buildManifest(base), buildManifest(base)])).toThrow(/both describe/)
  })

  it('requires every platform the release promised', () => {
    const merged = mergeManifests([buildManifest(base)])
    expect(() => assertManifestComplete(merged, ['darwin-aarch64'])).not.toThrow()
    expect(() => assertManifestComplete(merged, ['darwin-aarch64', 'darwin-x86_64'])).toThrow(
      /missing darwin-x86_64/
    )
  })

  it('rejects a manifest with no platforms at all', () => {
    expect(() => assertManifestComplete({ platforms: {} })).toThrow(/no platforms/)
    expect(() => mergeManifests([])).toThrow(/No update manifests/)
  })
})

describe('verify-release-assets', () => {
  const complete = [
    { name: 'latest.json', size: 300 },
    { name: 'Dive_0.1.4_aarch64.dmg', size: 90_000_000 },
    { name: 'Dive.app.tar.gz', size: 80_000_000 },
    { name: 'Dive.app.tar.gz.sig', size: 200 },
    { name: 'Dive_0.1.4_x64-setup.exe', size: 900 },
    { name: 'Dive_0.1.4_x64-setup.exe.sig', size: 100 }
  ]

  it('accepts a release that carries everything an update needs', async () => {
    const result = await verifyRelease({
      tag: 'v0.1.4',
      fetchRelease: async () => ({ assets: complete })
    })
    expect(result.assets).toHaveLength(6)
  })

  it('names what is missing rather than failing generically', () => {
    expect(missingAssetKinds(complete.filter((a) => a.name !== 'latest.json'))).toEqual([
      'update manifest'
    ])
    expect(missingAssetKinds([])).toEqual([
      'update manifest',
      'DMG installer',
      'macOS updater archive',
      'macOS updater signature',
      'Windows installer',
      'Windows updater signature'
    ])
  })

  it('treats a -setup.exe.sig as a signature and not as the installer', () => {
    // The signature ends with `.sig`, not `-setup.exe`, so a release carrying
    // only the signature must still report the installer as missing.
    const windowsOnly = [
      { name: 'latest.json', size: 1 },
      { name: 'Dive_0.1.4_x64-setup.exe.sig', size: 1 }
    ]
    expect(missingAssetKinds(windowsOnly)).toEqual([
      'DMG installer',
      'macOS updater archive',
      'macOS updater signature',
      'Windows installer'
    ])
  })

  it('treats a .tar.gz.sig as a signature and not as the archive', () => {
    // `.tar.gz.sig` ends with neither `.tar.gz` nor `.dmg`, so a release with
    // only the signature must still report the archive as missing.
    const signatureOnly = [{ name: 'latest.json', size: 1 }, { name: 'Dive.app.tar.gz.sig', size: 1 }]
    expect(missingAssetKinds(signatureOnly)).toEqual([
      'DMG installer',
      'macOS updater archive',
      'Windows installer',
      'Windows updater signature'
    ])
  })

  it('rejects a truncated upload, which reads as a corrupt download', async () => {
    await expect(
      verifyRelease({
        tag: 'v0.1.4',
        fetchRelease: async () => ({
          assets: complete.map((a) => (a.name === 'latest.json' ? { ...a, size: 0 } : a))
        })
      })
    ).rejects.toThrow(/empty assets: latest\.json/)
  })

  it('asks only for the platforms the release claims to ship', async () => {
    // A release cut from one Mac with DIVE_SKIP_WINDOWS carries no installer
    // for Windows, and demanding one would fail a release that is complete.
    const macOnly = complete.filter((a) => !a.name.includes('setup.exe'))
    const result = await verifyRelease({
      tag: 'v0.1.4',
      platforms: ['darwin'],
      fetchRelease: async () => ({ assets: macOnly })
    })
    expect(result.assets).toHaveLength(4)
    // Narrowing the claim does not excuse that platform's own assets.
    expect(missingAssetKinds(macOnly.slice(0, 2), requiredAssets(['darwin']))).toEqual([
      'macOS updater archive',
      'macOS updater signature'
    ])
  })

  it('refuses a claim it cannot check', () => {
    expect(() => requiredAssets(['linux'])).toThrow(/unknown platform: linux/)
    expect(() => requiredAssets([])).toThrow(/at least one platform/)
  })

  it('fails with the published asset list, so the cause is visible in the log', async () => {
    await expect(
      verifyRelease({ tag: 'v0.1.4', fetchRelease: async () => ({ assets: [] }) })
    ).rejects.toThrow(/Published assets: \(none\)/)
  })
})
